
      # For lack of the packages to build, it simply archives the source code which will work for now.
      # I may have to add a PPA of kde NEON
      # by adding `deb [trusted=yes] http://archive.neon.kde.org/user noble main` to '/etc/apt/sources.list.d/neon.list'
      # in order to install required dependencies
name: 'Release'
on:
  push:
    tags:
      - '**'

jobs:
  release:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'
      - name: 'Install Dependencies'
        run: |
          # Adding kde NEON PPA to the containerized Ubuntu because it lacks dependencies for Plasma 6
          echo "deb [trusted=yes] http://archive.neon.kde.org/user noble main" | tee /etc/apt/sources.list.d/neon.list
          apt update
          apt install -y kf6-extra-cmake-modules plasma-framework6-dev
      - name: 'Build Plasmoid'
        run: './install.sh'
      - name: 'Archive Artifacts'
        run: 'zip -r xyz.attacktive.nyan-wanderer.plasmoid "$HOME/.local/share/plasma/plasmoids/xyz.attacktive.nyan-wanderer"'
      - name: 'Create Release'
        uses: 'softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda'
        with:
          prerelease: true
          generate_release_notes: true
          files: 'xyz.attacktive.nyan-wanderer.plasmoid'
